name: Check New Version and Build

on:
  schedule:
    - cron: '1 0 * * *'  # 每天 UTC 时间 00:00 执行

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for new release
        id: check-release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/nezhahq/agent/releases/latest | jq -r '.tag_name')
          echo "Latest version is $LATEST_VERSION"
          echo "::set-output name=version::$LATEST_VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.check-release.outputs.version != ''
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            vpsss/nezha-agent:latest
            vpsss/nezha-agent:${{ steps.check-release.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
